version: '3'

services:
  mysql:
    container_name: ${CONTAINER_SITE_NAME}_mysql
    image: ${DB_IMAGE:-mysql}:${DB_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_SUFFIX: ${MYSQL_DATABASE}
    security_opt:
      - seccomp:unconfined

  production_wordpress:
    depends_on:
      - mysql
    container_name: "${CONTAINER_SITE_NAME}_production_wordpress"
    image: ${SITE_IMAGE:-wordpress}:${SITE_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ./wordpress/production:/var/www/html
      - ./wordpress/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: "production_${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}

  staging_wordpress:
    depends_on:
      - mysql
    container_name: "${CONTAINER_SITE_NAME}_staging_wordpress"
    image: ${SITE_IMAGE:-wordpress}:${SITE_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ./wordpress/staging:/var/www/html
      - ./wordpress/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: "staging_${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}

  development_wordpress:
    depends_on:
      - mysql
    container_name: "${CONTAINER_SITE_NAME}_development_wordpress"
    image: ${SITE_IMAGE:-wordpress}:${SITE_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ./wordpress/development:/var/www/html
      - ./wordpress/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: "development_${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: "dev.${DOMAIN}"
      LETSENCRYPT_HOST: "dev.${DOMAIN}"
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}

  production_nginx:
    depends_on:
      - production_wordpress
    image: nginx:1.19.4-alpine
    container_name: ${CONTAINER_SITE_NAME}_production_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./wordpress/production:/var/www/html
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      WORDPRESS_HOST: "${CONTAINER_SITE_NAME}_production_wordpress"
      LETSENCRYPT_HOST: "${DOMAIN}"
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  staging_nginx:
    depends_on:
      - staging_wordpress
    image: nginx:1.19.4-alpine
    container_name: ${CONTAINER_SITE_NAME}_staging_nginx
    build:
      context: ./nginx/
    restart: unless-stopped
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./wordpress/staging:/var/www/html
    environment:
      VIRTUAL_HOST: "staging.${DOMAIN}"
      WORDPRESS_HOST: "${CONTAINER_SITE_NAME}_staging_wordpress"
      LETSENCRYPT_HOST: "staging.${DOMAIN}"
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  development_nginx:
    depends_on:
      - development_wordpress
    image: nginx:1.19.4-alpine
    container_name: ${CONTAINER_SITE_NAME}_development_nginx
    build:
      context: ./nginx/
    restart: unless-stopped
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./wordpress/development:/var/www/html
    environment:
      VIRTUAL_HOST: "dev.${DOMAIN}"
      WORDPRESS_HOST: "${CONTAINER_SITE_NAME}_development_wordpress"
      LETSENCRYPT_HOST: "dev.${DOMAIN}"
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  # wpcli:
  #   image: tatemz/wp-cli
  #   volumes:
  #     - ${SITE_FILES}:/var/www/html
  #   depends_on:
  #     - mysql
  #   entrypoint: wp

networks:
   default:
     external:
       name: ${NETWORK}
